=begin
这里写注释
=end

source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

inhibit_all_warnings!

xcodeproj 'DDYQRCode.xcodeproj'

target :DDYQRCode do
    
    pod 'DDYQRCode', '~> 1.0.1'
end




=begin

多target可以这样写

source 'https://github.com/CocoaPods/Specs.git' 

platform :ios, '8.0'
inhibit_all_warnings!

xcodeproj 'Demo.xcodeproj'

target :Demo1 do
 pod 'Masonry', '~> 1.0.0'
 pod 'MBProgressHUD', '~> 0.9.2'
 pod 'iCarousel', '~> 1.8.2'
 pod 'MJRefresh', '~> 3.1.0'
 pod 'MJExtension', '~> 3.0.10'
 pod 'AFNetworking', '~> 3.1.0'
 pod 'SDWebImage', '~> 3.7.5'
 pod 'SVProgressHUD', '~> 2.0.3'
 pod 'FMDB', '~> 2.6.2'
end
target :Demo2 do
 pod 'MBProgressHUD', '~> 0.9.2'
end

=end


=begin

touch Podfile 建立Podfile文件

open -e Podfile 文本编辑打开Podfile文件

pod install --verbose --no-repo-update  不遍历所有库

=end
